application/classes/Controller/Admin.php, application/classes/Dao/SiteInfo.php, application/classes/Model/Methods.php
Починить кеширование информации о сайте
Добавить кеширование меню сайта
=> Site_info and site_menu caching

application/classes/Controller/Auth/Auth.php, application/views/templates/auth/auth.php
Issue #19 - Critical bug in Twitter Auth. Temporary revoke method.
Make Twitter authorisation - issue #38 on @demyashev
=> Remove twitter authorisation

application/classes/Controller/Index.php, application/classes/Controller/Pages.php, application/classes/Model/Page.php, application/views/templates/page_form.php, migrations/2016-02-16_rich_and_pin_news.sql
=> Rich news and pin news

application/views/templates/page_form.php
=> Form bug issue 45

application/classes/Model/Methods.php, application/classes/Model/Page.php
=> translit uri

application/classes/Controller/Pages.php, application/classes/Model/Page.php, application/views/templates/page_form.php, migrations/2016-04-05-source-link.sql, public/js/main.js
=> Source link

application/classes/Controller/User.php, application/classes/Model/User.php
=> removed isMe

application/classes/Controller/Comments.php, application/views/templates/page.php, index.php, public/css/main.css, public/js/comment.js
- Ссылки на профили пользователей на фото.
- Отправка комментария по Ctrl+Enter и Cmd+Enter.
- Добавлены переносы строк в комментарии.
- Удалены лишние пробелы и табы в коде.
=> Added functions in comments

public/css/main.css
=> change symbol's code

public/css/main.css
=> fixing top block's size

public/css/main.css
=> unnecessary symbols in css

public/extensions/codex-special/codex-special.v.0.8.css, public/extensions/codex-special/codex-special.v.0.8.js, public/js/codex.js
=> resolve problem 'disabling styles doesnt work'

application/views/main.php, application/views/templates/admin/layout.php, application/views/templates/page.php, application/views/templates/sidebar.php, application/views/templates/users/profile.php, public/css/main.css
=> New font, Design tasks closes

application/classes/Controller/Base/preDispatch.php, application/config/redis.php.sample
=> Add redis default database

.gitignore, upload/.gitignore, vendor/.gitignore
=> Add gitignore directly to the folders

application/classes/Controller/Auth/Auth.php
=> Исправлена проверка имени пользователя при регистрации

application/views/templates/pages/editor.php
=> Editor v1.6

application/classes/Controller/Auth/Auth.php, application/classes/Controller/Auth/Base.php
Append state to session (Twitter).
Remove session update. 
closes #218
=> Fix twitter auth and attach

application/classes/Kohana/Exception.php
=> Error handling

application/views/templates/pages/form.php
=> isNews checkbox is toggled on news list page

application/classes/Model/Feed/Pages.php
=> Fix getting pages list from feed

application/classes/Controller/Index.php, application/classes/Controller/Page/Modify.php, application/classes/Model/Feed/Pages.php, application/classes/Model/Methods.php, application/classes/Model/Page.php, application/routes.php, application/views/templates/index.php, application/views/templates/pages/form.php, application/views/templates/pages/list.php, application/views/templates/pages/page.php
=> Rename tab "News" to "Main"

application/classes/Controller/Page/Index.php, application/classes/Controller/Page/Modify.php, application/views/templates/pages/form.php
=> Do not add static pages and news to verifyed users pages list

application/views/main.php
=> enable env check for gov site widget

www/application/config/social.php.sample
=> HTTP_HOST -> SERVER_NAME

www/css.webpack.config.js
=> fix assets path

www/application/classes/Controller/Page/Index.php, www/application/views/templates/index.php, www/application/views/templates/pages/community_page.php, www/application/views/templates/pages/form.php, www/projects/cultofart/views/templates/components/about.php
* Description block
* Tabs (general)
* Children pages feed list
=> Content for the community page

www/application/classes/Controller/Page/Index.php, www/application/classes/Controller/Page/Modify.php, www/application/classes/Model/Page.php, www/application/views/templates/pages/form.php, www/application/views/templates/pages/page.php, www/migrations/!_codex-media.sql, www/migrations/2018-06-24-is-event.sql, www/projects/cultofart/views/templates/components/join-button.php, www/public/app/css/_variables.css, www/public/app/css/components/join-button.css
* Add field to db
* Add to Model
* Process in Controller
* Add checkbox to form, show only on GET param
* Add styles
=> Event Page

www/application/classes/Model/Feed/Pages.php, www/application/classes/Model/Methods.php, www/application/views/templates/components/menu.php, www/projects/cultofart/public/css/transparent-aside.css, www/projects/cultofart/views/templates/components/aside.php, www/projects/cultofart/views/templates/components/menu.php
* Modified template
* Added CSS
=> Parent & child menu items

www/application/classes/Controller/Auth/Auth.php, www/application/classes/Model/Methods.php, www/migrations/!_codex-media.sql
- log error while auth via Twitter
- update migrations
- check for an emptying a menu pages array
=> Some fixes

www/application/views/templates/pages/form.php
Pass chosen type to big editor
=> Hot fix: page-type select for non-admins 

www/application/classes/Model/Services/Vk.php
Changed request param name `version` -> `v` according to recent [API update](https://vk.com/dev/version_update)
=> Fix posting to VK

www/application/views/templates/components/esir_navigator.php, www/application/views/templates/pages/writing.php, www/public/app/css/components/esir-navigator.css
Remove `esir` from CSS classes
=> Rename esir navigator

www/application/views/templates/pages/list.php, www/public/app/css/_variables.css, www/public/app/css/components/posts-list.css, www/public/app/css/layout.css
Add an overlay to the feed item and make it behave like a link (except for header)
=> Add page overlay link

docker-compose.yml, www/composer.json, www/minion, www/modules/minion/classes/Kohana/Minion/Exception.php, www/modules/minion/classes/Task/Elastic.php, www/modules/minion/minion
Closes #488
To launch minion task use `docker exec -ti codexmedia_php_1 ./minion elastic`
To see result open http://localhost:9200/pages/_search?size=1000 in browser
=> MySQL to Elastic converter

www/application/views/templates/pages/form_wrapper.php, www/public/app/css/components/article.css, www/public/app/css/components/writing.css
=> Editor UI fixes

docker-compose.yml
on rebuild we can miss this directory. cache wont help
=> Save pma sources in docker

www/application/classes/Controller/Search.php, www/application/classes/Model/Elastic.php, www/application/classes/Model/Page.php, www/application/classes/Task/Elastic.php, www/application/routes.php
Closes #498
You can change this via: http://localhost:8880/search?query=test
This will search for word `test`
=> Elastic Search Backend

www/application/classes/Task/04FixMissingFieldsInLinkTool.php
Upgrades all linkTool blocks to correct format
=> Create "Fix Missing Fields In LinkTool" task

docker-compose.yml, docs/general-installation.md, www/application/bootstrap.php, www/application/classes/Controller/Auth/Auth.php, www/application/classes/Kohana/Exception.php, www/application/classes/Model/Page.php, www/application/views/main.php, www/composer.json, www/composer.lock, www/js.webpack.config.js, www/package.json, www/public/app/js/modules/hawk.js, www/yarn.lock
resolves #513
- update hawk php catcher
- update hawk javascript catcher
- update docker-compose file
- fix docs
- use token from Hawk 2
- throw PHP error and get in in the garage
- throw JS error and get in in the garage
- update yarn packages and rebuild frontend: `docker-compose exec php composer install`
- update composer packages `docker-compose exec php yarn && docker-compose exec php yarn build` 
- check .env for a valid hawk token
=> Update hawk catcher

www/application/views/main.php, www/index.php, www/js.webpack.config.js, www/package.json, www/yarn.lock
=> send sources to hawk

www/application/views/templates/components/share.php, www/public/app/js/main.js
=> resolve missing sharer
